name: Spring Boot CI

on:
  push:
    branches:
      - devops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Grant execute permission to Maven Wrapper
        run: chmod +x mvnw

      - name: Build Spring Boot Project
        run: ./mvnw clean package -DskipTests
